### ISSUE TITLE
Missing <ol> and <ul> style

### ISSUE THREAD

**Issue by geckolinux** [brycematheson/allegiant#2]
Hi there, it appears that `<ol>` and `<ul>` lists don't have any bullet points or numbering styles defined. Thanks!

**Comment by brycematheson** [comment]
This should now be fixed. Please use the following (standard) format:

```
<li>List Item 1</li>
<li>List Item 2</li>
<li>List Item 3</li>

<ol>
  <li>Coffee</li>
  <li>Tea</li>
  <li>Milk</li>
</ol>

```

Let me know if you have any issues.

**Comment by geckolinux** [comment]
Excellent, thanks very  much for the fast response!
